repos:
  - repo: https://github.com/mtkennerly/pre-commit-hooks
    rev: v0.3.0
    hooks:
      - id: poetry-ruff
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        entry: dmypy run
        args: []
        additional_dependencies:
          - httpx==0.23.0
          - humanize==4.3.0
          - langcodes==3.3.0
          - platformdirs==2.5.2
          - pyotp==2.7.0
          - pyoxipng==0.1.0
          - rich==12.5.1
          - types-attrs==19.1.0
          - types-beautifulsoup4==4.11.6
          - types-requests==2.28.11
          - types-toml==0.10.8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        name: pre-commit-hooks/check-added-large-files
      - id: check-executables-have-shebangs
        name: pre-commit-hooks/check-executables-have-shebangs
      - id: check-json
        name: pre-commit-hooks/check-json
      - id: check-merge-conflict
        name: pre-commit-hooks/check-merge-conflict
        args: [--assume-in-merge]
      - id: check-shebang-scripts-are-executable
        name: pre-commit-hooks/check-shebang-scripts-are-executable
      - id: check-symlinks
        name: pre-commit-hooks/check-symlinks
      - id: check-toml
        name: pre-commit-hooks/check-toml
      - id: check-xml
        name: pre-commit-hooks/check-xml
      - id: check-yaml
        name: pre-commit-hooks/check-yaml
      - id: destroyed-symlinks
        name: pre-commit-hooks/destroyed-symlinks
      - id: end-of-file-fixer
        name: pre-commit-hooks/end-of-file-fixer
      - id: fix-byte-order-marker
        name: pre-commit-hooks/fix-byte-order-marker
      - id: fix-encoding-pragma
        name: pre-commit-hooks/fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        name: pre-commit-hooks/mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        name: pre-commit-hooks/trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify
        args: [--in-place, --quote="]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        name: yesqa
