repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
      - id: autoflake

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.9.11
          - flake8-pie==0.16.0
          - Flake8-pyproject==1.1.0.post0
          - flake8-simplify==0.19.3
          - flake8-type-checking==2.1.3

  - repo: https://github.com/pycqa/isort
    rev: 12cc5fbd67eebf92eb2213b03c07b138ae1fb448
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests==2.28.10
          - types-toml==0.10.8

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify
        args: [--in-place, --quote="]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.5
    hooks:
      - id: vulture
